### ISSUE TITLE
[Loki] Add a configurable parameter for logs retention

### ISSUE THREAD

**Issue by lukeskywlkr** [sighupio/module-logging#177]
With the release v4.0.0 we start using TSDB. This issue has been opened to track the addition of a parametric log retention in the loki configuration. We should use the compactor component to do so because it is the long term supported way to do this, as stated in the [`official documentation`](https://grafana.com/docs/loki/latest/operations/storage/retention/).
Using the compactor we should pay attention to users that still have not migrated their store to TSDB since compactor does not support legacy stores. Below there are some configuration examples.

## Details ⚙️ 
- **Compactor specific configuration**: as shown in the official documentation the compactor is responsible for logs retention. Here an example configuration can be found.
  
  ```yaml
    compactor:
      working_directory: /data/retention
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: s3
   ```
   
- **Limits configuration**: the retention period is configured in the `limits_config` section of Loki configuration. Here is an example.
  
  ```yaml
    ...
      limits_config:
        retention_period: 744h
    ...
  ```
  
  The value specified in `retention_period` is applied for all log streams. A more granular retention policy can be applied using `retention_stream` where a selector can be specified and the retention policy applies for all the streams that match the selector. Here an example:
  
  ```yaml
    ...
      limits_config:
        retention_period: 744h
        retention_stream:
          - selector: '{namespace="dev"}'
             priority: 1
             period: 24h
    ...
  ```
  
  A per tenant override can also be specified to allow a further granular retention policy. Here the configuration:
  
  ```yaml
    ...
      limits_config:
        retention_period: 744h
        retention_stream:
          - selector: '{namespace="dev"}'
             priority: 1
             period: 24h
        per_tenant_override_config: /etc/overrides.yaml
    ...
  ```
  
  Here the `overrides.yaml` example using the [`runtime overrides`](https://grafana.com/docs/loki/latest/configure/#runtime-configuration-file):
  
  ```yaml
    overrides:
      "29":
          retention_period: 168h
          retention_stream:
          - selector: '{namespace="prod"}'
            priority: 2
            period: 336h
          - selector: '{container="loki"}'
            priority: 1
            period: 72h
      "30":
          retention_stream:
          - selector: '{container="nginx", level="debug"}'
            priority: 1
            period: 24h
  ```
